name: 'Hello World Docker Action from the Training'
description: 'Say hello to a user using the own action with Docker'

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'

outputs:
  time:
    description: 'The time we said hello.'
  Runner:
    description: 'How runs the part inside docker'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
