name: Deployment Environment Demo

# on:
#   push:
#     branches: [ main ]
#     paths-ignore: [.github/**]
#   pull_request:
#     branches: [ main ]
#   schedule:
#     - cron: '15 6 * * 0'
#   workflow_dispatch:

permissions:
  actions: read

on: 
  push:
    branches: [ main ] 
    paths-ignore: [.github/**]
  pull_request:
    branches:
      - main 
  workflow_dispatch:  
    inputs:
      environment:
        description: 'variable for environment selction'
        type: environment
        required: true


jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "Use input ${{ input.environment }}"
    

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test

    steps:
      - run: |
          echo "🧪  The Test was triggered by event: ${{ github.event_name }}"

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test

    steps:
      - run: |
          echo "🧪  The Load Test was triggered by event: ${{ github.event_name }}"
          sleep 5

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net

    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 1
      - run: |
          echo "🚀 Step 2..."
          sleep 1
      - run: |
          echo "🚀 Step 3..."
          sleep 1
      - run: |
          echo "🚀 Step 4..."
          sleep 1
      - run: |
          echo "🚀 Step 5...  using ${{ env.url }}"
          sleep 1
