name: Github Actions Demo

on: 
  push:
    branches:
      - main 
    paths-ignore:
      - .gitignore
  pull:
    branches:
      - main 
  workflow_dispatch:

  schedule:
    -cron: '* 15 6 * 0'
  

jobs:

  runs-on: ubuntu-latest

  steps:

    -name: Checkout
     uses: actions/checkout@v4

    
    
  
