name: Using own Docker Action

on:
  workflow_dispatch:
    inputs:
       name:
        required: true
    
jobs:
  docker-run:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello Action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '${{ github.event.inputs.name }}'

      - name: Use the output
        run:  |
          echo "The time was ${{ steps.hello-action.outputs.time }}"
          echo "The executor was was ${{ steps.hello-action.outputs.Runner }}"
        
